// lib/pdf/complianceReportPDF.ts - Generate PDF report for ingredient compliance

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface ComplianceReportOptions {
  business: {
    id: string
    name: string
  }
  ingredients: any[]
}

export async function generateComplianceReportPDF(options: ComplianceReportOptions) {
  const { business, ingredients } = options

  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.setTextColor(0, 56, 66) // #003842
  doc.text(`${business.name} - Compliance Report`, 20, 30)

  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 40)

  // Compliance summary
  const compliant = ingredients.filter(i => i.compliance === 'compliant').length
  const warning = ingredients.filter(i => i.compliance === 'warning').length
  const error = ingredients.filter(i => i.compliance === 'error').length

  doc.text(`Total Ingredients: ${ingredients.length}`, 20, 50)
  doc.text(`Compliant: ${compliant}`, 20, 60)
  doc.text(`Warnings: ${warning}`, 20, 70)
  doc.text(`Errors: ${error}`, 20, 80)

  // Prepare table data
  const tableData = ingredients.map(ingredient => [
    ingredient.name || 'N/A',
    ingredient.compliance || 'N/A',
    ingredient.status || 'N/A',
    ingredient.certifications?.join(', ') || 'N/A',
    ingredient.suppliers?.length || 0,
    ingredient.updated_at ? new Date(ingredient.updated_at).toLocaleDateString() : 'N/A'
  ])

  // Generate table
  autoTable(doc, {
    head: [['Ingredient Name', 'Compliance Status', 'Status', 'Certifications', 'Suppliers', 'Last Updated']],
    body: tableData,
    startY: 90,
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [0, 56, 66], // #003842
      textColor: 255,
      fontSize: 9,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // Light gray
    },
    columnStyles: {
      0: { cellWidth: 40 }, // Name
      1: { cellWidth: 25 }, // Compliance
      2: { cellWidth: 20 }, // Status
      3: { cellWidth: 35 }, // Certifications
      4: { cellWidth: 20 }, // Suppliers
      5: { cellWidth: 25 }, // Last Updated
    },
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`Page ${i} of ${pageCount}`, 20, doc.internal.pageSize.height - 10)
    doc.text('Generated by Ally Allergen Management System', doc.internal.pageSize.width - 100, doc.internal.pageSize.height - 10)
  }

  // Save the PDF
  const fileName = `${business.name.replace(/[^a-zA-Z0-9]/g, '_')}_Compliance_Report_${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(fileName)
}