// lib/pdf/ingredientsReportPDF.ts - Generate PDF report for ingredients list

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface IngredientsReportOptions {
  business: {
    id: string
    name: string
  }
  ingredients: any[]
}

export async function generateIngredientsReportPDF(options: IngredientsReportOptions) {
  const { business, ingredients } = options

  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.setTextColor(0, 56, 66) // #003842
  doc.text(`${business.name} - Ingredients Report`, 20, 30)

  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 40)
  doc.text(`Total Ingredients: ${ingredients.length}`, 20, 50)

  // Prepare table data
  const tableData = ingredients.map(ingredient => [
    ingredient.name || 'N/A',
    ingredient.description || 'N/A',
    ingredient.category || 'N/A',
    ingredient.status || 'N/A',
    ingredient.compliance || 'N/A',
    ingredient.suppliers?.length || 0
  ])

  // Generate table
  autoTable(doc, {
    head: [['Name', 'Description', 'Category', 'Status', 'Compliance', 'Suppliers']],
    body: tableData,
    startY: 60,
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [0, 56, 66], // #003842
      textColor: 255,
      fontSize: 9,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // Light gray
    },
    columnStyles: {
      0: { cellWidth: 40 }, // Name
      1: { cellWidth: 60 }, // Description
      2: { cellWidth: 30 }, // Category
      3: { cellWidth: 25 }, // Status
      4: { cellWidth: 25 }, // Compliance
      5: { cellWidth: 20 }, // Suppliers
    },
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`Page ${i} of ${pageCount}`, 20, doc.internal.pageSize.height - 10)
    doc.text('Generated by Ally Allergen Management System', doc.internal.pageSize.width - 100, doc.internal.pageSize.height - 10)
  }

  // Save the PDF
  const fileName = `${business.name.replace(/[^a-zA-Z0-9]/g, '_')}_Ingredients_Report_${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(fileName)
}