// lib/pdf/menuItemsReportPDF.ts - Generate PDF report for menu items list

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface MenuItemsReportOptions {
  business: {
    id: string
    name: string
  }
  menuItems: any[]
}

export async function generateMenuItemsReportPDF(options: MenuItemsReportOptions) {
  const { business, menuItems } = options

  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.setTextColor(0, 56, 66) // #003842
  doc.text(`${business.name} - Menu Items Report`, 20, 30)

  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 40)
  doc.text(`Total Menu Items: ${menuItems.length}`, 20, 50)

  // Prepare table data
  const tableData = menuItems.map(item => [
    item.name || 'N/A',
    item.description || 'N/A',
    item.category || 'N/A',
    item.price ? `€${item.price.toFixed(2)}` : 'N/A',
    item.is_active ? 'Active' : 'Inactive',
    item.display_order || 'N/A'
  ])

  // Generate table
  autoTable(doc, {
    head: [['Name', 'Description', 'Category', 'Price', 'Status', 'Display Order']],
    body: tableData,
    startY: 60,
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [0, 56, 66], // #003842
      textColor: 255,
      fontSize: 9,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // Light gray
    },
    columnStyles: {
      0: { cellWidth: 35 }, // Name
      1: { cellWidth: 55 }, // Description
      2: { cellWidth: 25 }, // Category
      3: { cellWidth: 20 }, // Price
      4: { cellWidth: 20 }, // Status
      5: { cellWidth: 25 }, // Display Order
    },
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`Page ${i} of ${pageCount}`, 20, doc.internal.pageSize.height - 10)
    doc.text('Generated by Ally Allergen Management System', doc.internal.pageSize.width - 100, doc.internal.pageSize.height - 10)
  }

  // Save the PDF
  const fileName = `${business.name.replace(/[^a-zA-Z0-9]/g, '_')}_Menu_Items_Report_${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(fileName)
}