// lib/pdf/pdfBranding.ts — shared branding utilities for PDF generation

import type jsPDF from 'jspdf'

/** AllyJen default primary colour [r, g, b] */
export const ALLYJEN_PRIMARY: [number, number, number] = [0, 56, 66]   // #003842

/** Parse a hex colour string into [r, g, b]. Falls back to AllyJen primary on invalid input. */
export function hexToRgb(hex: string | null | undefined): [number, number, number] {
  if (!hex) return ALLYJEN_PRIMARY
  const clean = hex.replace('#', '')
  if (clean.length !== 6) return ALLYJEN_PRIMARY
  const r = parseInt(clean.substring(0, 2), 16)
  const g = parseInt(clean.substring(2, 4), 16)
  const b = parseInt(clean.substring(4, 6), 16)
  if (isNaN(r) || isNaN(g) || isNaN(b)) return ALLYJEN_PRIMARY
  return [r, g, b]
}

/** Fetch a URL and return it as a base64 data URL usable by jsPDF.addImage. Returns null on failure. */
export async function fetchLogoAsDataUrl(logoUrl: string): Promise<string | null> {
  try {
    const res = await fetch(logoUrl)
    if (!res.ok) return null
    const blob = await res.blob()
    return new Promise<string | null>((resolve) => {
      const reader = new FileReader()
      reader.onloadend = () => resolve(reader.result as string)
      reader.onerror  = () => resolve(null)
      reader.readAsDataURL(blob)
    })
  } catch {
    return null
  }
}

/**
 * Load a data URL into an Image element and return its natural pixel dimensions.
 * Used to preserve aspect ratio before calling jsPDF.addImage.
 */
export function getImageDimensions(dataUrl: string): Promise<{ w: number; h: number }> {
  return new Promise((resolve) => {
    if (typeof window === 'undefined') {
      resolve({ w: 1, h: 1 })
      return
    }
    const img = new window.Image()
    img.onload  = () => resolve({ w: img.naturalWidth, h: img.naturalHeight })
    img.onerror = () => resolve({ w: 1, h: 1 })
    img.src = dataUrl
  })
}

/**
 * Calculate fitted image dimensions that preserve aspect ratio.
 * @param naturalW  natural pixel width
 * @param naturalH  natural pixel height
 * @param maxW      max display width in mm
 * @param maxH      max display height in mm
 */
export function fitDimensions(
  naturalW: number, naturalH: number,
  maxW: number, maxH: number
): { w: number; h: number } {
  if (naturalW <= 0 || naturalH <= 0) return { w: maxW, h: maxH }
  const ratio = naturalW / naturalH
  let w = maxW
  let h = w / ratio
  if (h > maxH) {
    h = maxH
    w = h * ratio
  }
  return { w, h }
}

/** Fetch the AllyJen logo PNG from /allyjen-logo.png (served as a static asset). */
export async function fetchAllyJenLogoDataUrl(): Promise<string | null> {
  return fetchLogoAsDataUrl('/allyjen-logo.png')
}

/**
 * Draw per-page footers on every page of a jsPDF document.
 * - Page numbers on every page (bottom-left)
 * - "Generated by AllyJen" text on every page (bottom-right)
 * - Timestamp centred on the bottom of the last page
 * - AllyJen logo centred just above the timestamp on the last page
 */
export async function drawPageFooters(
  doc: jsPDF,
  allyjenLogoDataUrl: string | null,
  generatedDate: string
): Promise<void> {
  const pageCount = doc.getNumberOfPages()
  const pw = doc.internal.pageSize.getWidth()
  const ph = doc.internal.pageSize.getHeight()
  const bottomY = ph - 8

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(160, 160, 160)

    // Page number — bottom left
    doc.text(`Page ${i} of ${pageCount}`, 10, bottomY)

    // Generated text — bottom right
    doc.text('Generated by AllyJen', pw - 10, bottomY, { align: 'right' })

    // Last-page extras
    if (i === pageCount) {
      // AllyJen logo centred, 10 mm above the timestamp line
      if (allyjenLogoDataUrl) {
        try {
          const { w: nw, h: nh } = await getImageDimensions(allyjenLogoDataUrl)
          const { w, h } = fitDimensions(nw, nh, 30, 10)
          doc.addImage(allyjenLogoDataUrl, 'PNG', (pw - w) / 2, bottomY - h - 12, w, h)
        } catch { /* ignore */ }
      }
      // Timestamp centred on bottom
      doc.setFontSize(7)
      doc.setTextColor(160, 160, 160)
      doc.text(`Generated: ${generatedDate}`, pw / 2, bottomY - 2, { align: 'center' })
    }
  }
}
