// lib/pdf/pdfBranding.ts — shared branding utilities for PDF generation

import type jsPDF from 'jspdf'

function drawLegendCheckmark(
  doc: jsPDF,
  cellX: number,
  cellY: number,
  cellW: number,
  cellH: number,
  high: boolean
): void {
  const cx = cellX + cellW / 2
  const cy = cellY + cellH / 2
  const s = 1.1
  const color: [number, number, number] = high ? [153, 27, 27] : [133, 77, 14]
  doc.setDrawColor(...color)
  doc.setLineWidth(0.55)
  doc.line(cx - s, cy + s * 0.05, cx - s * 0.1, cy + s * 0.9)
  doc.line(cx - s * 0.1, cy + s * 0.9, cx + s, cy - s * 0.5)
}

/** AllyJen default primary colour [r, g, b] */
export const ALLYJEN_PRIMARY: [number, number, number] = [0, 56, 66]   // #003842

/** Parse a hex colour string into [r, g, b]. Falls back to AllyJen primary on invalid input. */
export function hexToRgb(hex: string | null | undefined): [number, number, number] {
  if (!hex) return ALLYJEN_PRIMARY
  const clean = hex.replace('#', '')
  if (clean.length !== 6) return ALLYJEN_PRIMARY
  const r = parseInt(clean.substring(0, 2), 16)
  const g = parseInt(clean.substring(2, 4), 16)
  const b = parseInt(clean.substring(4, 6), 16)
  if (isNaN(r) || isNaN(g) || isNaN(b)) return ALLYJEN_PRIMARY
  return [r, g, b]
}

/** Fetch a URL and return it as a base64 data URL usable by jsPDF.addImage. Returns null on failure. */
export async function fetchLogoAsDataUrl(logoUrl: string): Promise<string | null> {
  try {
    const res = await fetch(logoUrl)
    if (!res.ok) return null
    const blob = await res.blob()
    return new Promise<string | null>((resolve) => {
      const reader = new FileReader()
      reader.onloadend = () => resolve(reader.result as string)
      reader.onerror  = () => resolve(null)
      reader.readAsDataURL(blob)
    })
  } catch {
    return null
  }
}

/**
 * Load a data URL into an Image element and return its natural pixel dimensions.
 * Used to preserve aspect ratio before calling jsPDF.addImage.
 */
export function getImageDimensions(dataUrl: string): Promise<{ w: number; h: number }> {
  return new Promise((resolve) => {
    if (typeof window === 'undefined') {
      resolve({ w: 1, h: 1 })
      return
    }
    const img = new window.Image()
    img.onload  = () => resolve({ w: img.naturalWidth, h: img.naturalHeight })
    img.onerror = () => resolve({ w: 1, h: 1 })
    img.src = dataUrl
  })
}

/**
 * Calculate fitted image dimensions that preserve aspect ratio.
 * @param naturalW  natural pixel width
 * @param naturalH  natural pixel height
 * @param maxW      max display width in mm
 * @param maxH      max display height in mm
 */
export function fitDimensions(
  naturalW: number, naturalH: number,
  maxW: number, maxH: number
): { w: number; h: number } {
  if (naturalW <= 0 || naturalH <= 0) return { w: maxW, h: maxH }
  const ratio = naturalW / naturalH
  let w = maxW
  let h = w / ratio
  if (h > maxH) {
    h = maxH
    w = h * ratio
  }
  return { w, h }
}

/** Fetch the AllyJen logo PNG from /allyjen-logo.png (served as a static asset). */
export async function fetchAllyJenLogoDataUrl(): Promise<string | null> {
  return fetchLogoAsDataUrl('/allyjen-logo.png')
}

/**
 * Draw per-page footers on every page of a jsPDF document.
 * - Page numbers on every page (bottom-left)
 * - "Generated by AllyJen" text on every page (bottom-right)
 * - Generation timestamp + a data-freshness warning, centred, on EVERY page
 * - AllyJen logo centred just above the timestamp on the last page
 */
export async function drawPageFooters(
  doc: jsPDF,
  allyjenLogoDataUrl: string | null,
  generatedDate: string,
  showLegend = true,
  ficNote?: string
): Promise<void> {
  const pageCount = doc.getNumberOfPages()
  const pw = doc.internal.pageSize.getWidth()
  const ph = doc.internal.pageSize.getHeight()
  const legendY = ph - 16
  const bottomY = ph - 8
  const timestampY = bottomY - 4

  const legendItems: { fill: [number, number, number]; high: boolean | null; text: string }[] = [
    { fill: [254, 202, 202], high: true,  text: 'Contains (high severity)' },
    { fill: [254, 240, 138], high: false, text: 'May contain / Traces / Cross-contamination' },
    { fill: [255, 255, 255], high: null,  text: 'Not present' },
  ]

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(160, 160, 160)

    if (showLegend) {
      // FIC / regulation note — sits just above the legend, centred, subtle italic
      if (ficNote) {
        doc.setFont('helvetica', 'italic')
        doc.setFontSize(5.5)
        doc.setTextColor(140, 140, 140)
        doc.text(ficNote, pw / 2, legendY - 7, { align: 'center', maxWidth: pw - 20 })
      }

      // Measure text widths so the whole legend block can be centred
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(7)
      const boxW = 5
      const boxTextGap = 2   // mm between right edge of box and start of text
      const interItemGap = 10  // mm between end of one item's text and next item's box
      const textWidths = legendItems.map(item => doc.getTextWidth(item.text))
      const itemWidths = textWidths.map(tw => boxW + boxTextGap + tw)
      const totalLegendW = itemWidths.reduce((a, b) => a + b, 0) + interItemGap * (legendItems.length - 1)
      let startX = (pw - totalLegendW) / 2

      legendItems.forEach((item, index) => {
        const x = startX
        doc.setFillColor(...item.fill)
        doc.setDrawColor(180, 180, 180)
        doc.rect(x, legendY - 4, boxW, 5, 'FD')
        if (item.high !== null) {
          drawLegendCheckmark(doc, x, legendY - 4, boxW, 5, item.high)
        }
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(7)
        doc.setTextColor(80, 80, 80)
        doc.text(item.text, x + boxW + boxTextGap, legendY)
        startX += itemWidths[index] + interItemGap
      })
    }

    // Page number — bottom left
    doc.text(`Page ${i} of ${pageCount}`, 10, bottomY)

    // Generated text — bottom right
    doc.text('Report by AllyJen.ie', pw - 10, bottomY, { align: 'right' })

    // Timestamp + freshness warning — centred, on every page
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6.5)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Generated: ${generatedDate}  —  Allergen and menu information can change at any time. Always confirm with staff before relying on this report.`,
      pw / 2,
      timestampY,
      { align: 'center', maxWidth: pw - 20 }
    )

    if (i === pageCount && allyjenLogoDataUrl) {
      try {
        const { w: nw, h: nh } = await getImageDimensions(allyjenLogoDataUrl)
        const { w, h } = fitDimensions(nw, nh, 30, 10)
        doc.addImage(allyjenLogoDataUrl, 'PNG', (pw - w) / 2, timestampY - h - 5, w, h)
      } catch { /* ignore */ }
    }
  }
}

