// lib/pdf/suppliersReportPDF.ts - Generate PDF report for suppliers directory

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { hexToRgb, fetchLogoAsDataUrl } from './pdfBranding'

interface SuppliersReportOptions {
  business: {
    id: string
    name: string
    settings?: { primaryColor?: string | null; logoUrl?: string | null } | null
  }
  suppliers: any[]
}

export async function generateSuppliersReportPDF(options: SuppliersReportOptions) {
  const { business, suppliers } = options

  const primaryRgb = hexToRgb(business.settings?.primaryColor)
  const logoDataUrl = business.settings?.logoUrl
    ? await fetchLogoAsDataUrl(business.settings.logoUrl)
    : null

  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 25

  if (logoDataUrl) {
    try { doc.addImage(logoDataUrl, 'auto', 10, y - 10, 30, 14) } catch { /* ignore */ }
    y = 42
  }

  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...primaryRgb)
  doc.text(business.name, pageWidth / 2, y, { align: 'center' })
  y += 8

  doc.setFontSize(13)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(80, 80, 80)
  doc.text('Suppliers Directory', pageWidth / 2, y, { align: 'center' })
  y += 8

  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, y)
  y += 6
  doc.text(`Total Suppliers: ${suppliers.length}`, 20, y)
  y += 10

  const tableData = suppliers.map(supplier => [
    supplier.name || 'N/A',
    supplier.contact || 'N/A',
    supplier.phone || 'N/A',
    supplier.email || 'N/A',
    supplier.website || 'N/A',
    supplier.ingredient_count || 0,
    supplier.notes || 'N/A'
  ])

  autoTable(doc, {
    head: [['Name', 'Contact', 'Phone', 'Email', 'Website', 'Ingredients', 'Notes']],
    body: tableData,
    startY: y,
    styles: { fontSize: 7, cellPadding: 2 },
    headStyles: { fillColor: primaryRgb, textColor: 255, fontSize: 8, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 35 },
      1: { cellWidth: 25 },
      2: { cellWidth: 25 },
      3: { cellWidth: 35 },
      4: { cellWidth: 30 },
      5: { cellWidth: 20 },
      6: { cellWidth: 30 },
    },
  })

  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`Page ${i} of ${pageCount}`, 20, doc.internal.pageSize.height - 10)
    doc.text('Generated by AllyJen', doc.internal.pageSize.width - 20, doc.internal.pageSize.height - 10, { align: 'right' })
  }

  const fileName = `${business.name.replace(/[^a-zA-Z0-9]/g, '_')}_Suppliers_Directory_${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(fileName)
}
}