// lib/pdf/suppliersReportPDF.ts - Generate PDF report for suppliers directory

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface SuppliersReportOptions {
  business: {
    id: string
    name: string
  }
  suppliers: any[]
}

export async function generateSuppliersReportPDF(options: SuppliersReportOptions) {
  const { business, suppliers } = options

  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.setTextColor(0, 56, 66) // #003842
  doc.text(`${business.name} - Suppliers Directory`, 20, 30)

  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 40)
  doc.text(`Total Suppliers: ${suppliers.length}`, 20, 50)

  // Prepare table data
  const tableData = suppliers.map(supplier => [
    supplier.name || 'N/A',
    supplier.contact || 'N/A',
    supplier.phone || 'N/A',
    supplier.email || 'N/A',
    supplier.website || 'N/A',
    supplier.ingredient_count || 0,
    supplier.notes || 'N/A'
  ])

  // Generate table
  autoTable(doc, {
    head: [['Name', 'Contact', 'Phone', 'Email', 'Website', 'Ingredients', 'Notes']],
    body: tableData,
    startY: 60,
    styles: {
      fontSize: 7,
      cellPadding: 2,
    },
    headStyles: {
      fillColor: [0, 56, 66], // #003842
      textColor: 255,
      fontSize: 8,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // Light grey
    },
    columnStyles: {
      0: { cellWidth: 35 }, // Name
      1: { cellWidth: 25 }, // Contact
      2: { cellWidth: 25 }, // Phone
      3: { cellWidth: 35 }, // Email
      4: { cellWidth: 30 }, // Website
      5: { cellWidth: 20 }, // Ingredients
      6: { cellWidth: 30 }, // Notes
    },
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`Page ${i} of ${pageCount}`, 20, doc.internal.pageSize.height - 10)
    doc.text('Generated by AllyJen Management System', doc.internal.pageSize.width - 100, doc.internal.pageSize.height - 10)
  }

  // Save the PDF
  const fileName = `${business.name.replace(/[^a-zA-Z0-9]/g, '_')}_Suppliers_Directory_${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(fileName)
}