export const adminAccessTranslations = {
  en: {
    messaging: {
      sendError: 'We could not send your message.', messageSent: 'Message sent', thanks: 'Thanks for getting in touch. Our team will respond as quickly as we can.', sendAnother: 'Send another message', intro: "Hi, I'm {name}. Leave a message below and a member of the AllyJen team will respond as quickly as possible.", urgentAllergen: 'For urgent allergen questions, please speak directly with a member of staff before ordering.', yourName: 'Your name', replyEmail: 'Email for our reply', howCanWeHelp: 'How can we help?', website: 'Website', sending: 'Sending…', sendMessage: 'Send message',
    },
    adminPortal: {
      dashboard: 'Dashboard', ingredients: 'Ingredients', newIngredient: 'New Ingredient', menuBuilder: 'Menu Builder', newItem: 'New Item', sites: 'Sites', newSite: 'New Site', suppliers: 'Suppliers', analytics: 'Analytics', downloads: 'Downloads', accessPoints: 'Access Points', kioskDevices: 'Kiosk Devices', compliance: 'Compliance', foodSafety: 'Food Safety', settings: 'Settings', helpSupport: 'Help & Support', superAdmin: 'Super Admin', admin: 'Admin', accessPointsDescription: 'Manage how customers access your allergen menus.', activeQrCodes: 'Active QR codes', qrCodeSingular: '{count} QR code', qrCodePlural: '{count} QR codes', devicesOnline: '{online}/{total} devices online', openLocation: 'Open location', manageQrAccessPoints: 'Manage QR access points →',
    },
    accessPoints: {
      loadError: 'Failed to load QR codes', createError: 'Failed to create QR code', updateError: 'Failed to update QR code', deleteError: 'Failed to delete QR code', previewUnavailable: 'QR code preview is unavailable', imageError: 'Could not prepare QR code image', signError: 'Failed to create QR sign', loading: 'Loading QR codes…', qrLiteDescription: 'create and download a code below—no kiosk device or pairing step is required.', qrCodes: 'QR codes', active: 'Active', inactive: 'Inactive', totalScans: 'Total scans', codesForSite: 'QR codes for {site}', createDescription: 'Create separate codes for entrances, counters, tables, or printed materials.', createQrCode: 'Create QR code', close: 'Close', site: 'Site', chooseSite: 'Choose a site…', name: 'Name', namePlaceholder: 'Front entrance', placement: 'Placement', optional: '(optional)', placementPlaceholder: 'Window beside main door', cancel: 'Cancel', creating: 'Creating…', create: 'Create', emptyTitle: 'No QR codes yet', emptyDescription: 'Create one to give customers mobile access without setting up hardware.', scans: 'scans', lastScanned: 'Last {date}', notScanned: 'Not scanned yet', copied: 'Copied', copy: 'Copy', open: 'Open', deactivate: 'Deactivate', activate: 'Activate', delete: 'Delete', deleteConfirm: 'Delete “{name}”? Its printed QR code will stop being tracked.', signTitle: 'Scan for allergen information', signDescription: 'Open the live AllyJen allergen menu on your phone. No app required.',
    },
  },
  ga: {
    messaging: {
      sendError: 'Níorbh fhéidir do theachtaireacht a sheoladh.', messageSent: 'Teachtaireacht seolta', thanks: 'Go raibh maith agat as teagmháil a dhéanamh linn. Freagróidh ár bhfoireann a luaithe is féidir.', sendAnother: 'Seol teachtaireacht eile', intro: 'Dia duit, is mise {name}. Fág teachtaireacht thíos agus freagróidh ball d’fhoireann AllyJen a luaithe is féidir.', urgentAllergen: 'Má tá ceist phráinneach agat faoi ailléirginí, labhair go díreach le ball foirne sula n-ordaíonn tú.', yourName: 'D’ainm', replyEmail: 'Ríomhphost dár bhfreagra', howCanWeHelp: 'Conas is féidir linn cabhrú?', website: 'Suíomh gréasáin', sending: 'Á sheoladh…', sendMessage: 'Seol teachtaireacht',
    },
    adminPortal: {
      dashboard: 'Painéal', ingredients: 'Comhábhair', newIngredient: 'Comhábhar Nua', menuBuilder: 'Tógálaí Biachláir', newItem: 'Mír Nua', sites: 'Suíomhanna', newSite: 'Suíomh Nua', suppliers: 'Soláthraithe', analytics: 'Anailísíocht', downloads: 'Íoslódálacha', accessPoints: 'Pointí Rochtana', kioskDevices: 'Gléasanna Both', compliance: 'Comhlíonadh', foodSafety: 'Sábháilteacht Bia', settings: 'Socruithe', helpSupport: 'Cabhair agus Tacaíocht', superAdmin: 'Sár-Riarachán', admin: 'Riarachán', accessPointsDescription: 'Bainistigh an chaoi a bhfaigheann custaiméirí rochtain ar do bhiachláir ailléirginí.', activeQrCodes: 'Cóid QR ghníomhacha', qrCodeSingular: '{count} chód QR', qrCodePlural: '{count} cód QR', devicesOnline: '{online}/{total} gléas ar líne', openLocation: 'Oscail an suíomh', manageQrAccessPoints: 'Bainistigh pointí rochtana QR →',
    },
    accessPoints: {
      loadError: 'Níorbh fhéidir cóid QR a luchtú', createError: 'Níorbh fhéidir cód QR a chruthú', updateError: 'Níorbh fhéidir an cód QR a nuashonrú', deleteError: 'Níorbh fhéidir an cód QR a scriosadh', previewUnavailable: 'Níl réamhamharc an chóid QR ar fáil', imageError: 'Níorbh fhéidir íomhá an chóid QR a ullmhú', signError: 'Níorbh fhéidir comhartha QR a chruthú', loading: 'Cóid QR á luchtú…', qrLiteDescription: 'cruthaigh agus íoslódáil cód thíos—níl gléas both ná céim péireála ag teastáil.', qrCodes: 'Cóid QR', active: 'Gníomhach', inactive: 'Neamhghníomhach', totalScans: 'Scananna iomlána', codesForSite: 'Cóid QR do {site}', createDescription: 'Cruthaigh cóid ar leith d’iontrálacha, cuntair, boird nó ábhar clóite.', createQrCode: 'Cruthaigh cód QR', close: 'Dún', site: 'Suíomh', chooseSite: 'Roghnaigh suíomh…', name: 'Ainm', namePlaceholder: 'An príomhbhealach isteach', placement: 'Suíomh an chóid', optional: '(roghnach)', placementPlaceholder: 'Fuinneog in aice leis an bpríomhdhoras', cancel: 'Cealaigh', creating: 'Á chruthú…', create: 'Cruthaigh', emptyTitle: 'Níl aon chóid QR ann fós', emptyDescription: 'Cruthaigh ceann chun rochtain mhóibíleach a thabhairt do chustaiméirí gan crua-earraí a shocrú.', scans: 'scan', lastScanned: 'An uair dheireanach {date}', notScanned: 'Níor scanadh fós', copied: 'Cóipeáilte', copy: 'Cóipeáil', open: 'Oscail', deactivate: 'Díghníomhachtaigh', activate: 'Gníomhachtaigh', delete: 'Scrios', deleteConfirm: 'Scrios “{name}”? Ní dhéanfar a chód QR clóite a rianú a thuilleadh.', signTitle: 'Scan le haghaidh faisnéis ailléirginí', signDescription: 'Oscail biachlár beo ailléirginí AllyJen ar d’fhón. Níl aip ag teastáil.',
    },
  },
  pt: {
    messaging: {
      sendError: 'Não foi possível enviar a sua mensagem.', messageSent: 'Mensagem enviada', thanks: 'Obrigado por entrar em contacto. A nossa equipa responderá assim que possível.', sendAnother: 'Enviar outra mensagem', intro: 'Olá, sou {name}. Deixe uma mensagem abaixo e um membro da equipa AllyJen responderá assim que possível.', urgentAllergen: 'Para questões urgentes sobre alergénios, fale diretamente com um membro da equipa antes de encomendar.', yourName: 'O seu nome', replyEmail: 'Email para a nossa resposta', howCanWeHelp: 'Como podemos ajudar?', website: 'Site', sending: 'A enviar…', sendMessage: 'Enviar mensagem',
    },
    adminPortal: {
      dashboard: 'Painel', ingredients: 'Ingredientes', newIngredient: 'Novo Ingrediente', menuBuilder: 'Criador de Menu', newItem: 'Novo Item', sites: 'Locais', newSite: 'Novo Local', suppliers: 'Fornecedores', analytics: 'Análises', downloads: 'Downloads', accessPoints: 'Pontos de Acesso', kioskDevices: 'Dispositivos de Quiosque', compliance: 'Conformidade', foodSafety: 'Segurança Alimentar', settings: 'Definições', helpSupport: 'Ajuda e Suporte', superAdmin: 'Superadministrador', admin: 'Administração', accessPointsDescription: 'Faça a gestão do acesso dos clientes aos seus menus de alergénios.', activeQrCodes: 'Códigos QR ativos', qrCodeSingular: '{count} código QR', qrCodePlural: '{count} códigos QR', devicesOnline: '{online}/{total} dispositivos online', openLocation: 'Abrir local', manageQrAccessPoints: 'Gerir pontos de acesso QR →',
    },
    accessPoints: {
      loadError: 'Não foi possível carregar os códigos QR', createError: 'Não foi possível criar o código QR', updateError: 'Não foi possível atualizar o código QR', deleteError: 'Não foi possível eliminar o código QR', previewUnavailable: 'A pré-visualização do código QR não está disponível', imageError: 'Não foi possível preparar a imagem do código QR', signError: 'Não foi possível criar o cartaz QR', loading: 'A carregar códigos QR…', qrLiteDescription: 'crie e descarregue um código abaixo—não é necessário um dispositivo de quiosque nem emparelhamento.', qrCodes: 'Códigos QR', active: 'Ativos', inactive: 'Inativo', totalScans: 'Total de leituras', codesForSite: 'Códigos QR para {site}', createDescription: 'Crie códigos separados para entradas, balcões, mesas ou materiais impressos.', createQrCode: 'Criar código QR', close: 'Fechar', site: 'Local', chooseSite: 'Escolha um local…', name: 'Nome', namePlaceholder: 'Entrada principal', placement: 'Colocação', optional: '(opcional)', placementPlaceholder: 'Janela junto à porta principal', cancel: 'Cancelar', creating: 'A criar…', create: 'Criar', emptyTitle: 'Ainda não existem códigos QR', emptyDescription: 'Crie um para dar acesso móvel aos clientes sem configurar equipamento.', scans: 'leituras', lastScanned: 'Última em {date}', notScanned: 'Ainda não lido', copied: 'Copiado', copy: 'Copiar', open: 'Abrir', deactivate: 'Desativar', activate: 'Ativar', delete: 'Eliminar', deleteConfirm: 'Eliminar “{name}”? O respetivo código QR impresso deixará de ser monitorizado.', signTitle: 'Leia para obter informações sobre alergénios', signDescription: 'Abra o menu de alergénios AllyJen em direto no seu telemóvel. Não requer aplicação.',
    },
  },
  fr: {
    messaging: {
      sendError: 'Impossible d’envoyer votre message.', messageSent: 'Message envoyé', thanks: 'Merci de nous avoir contactés. Notre équipe vous répondra dès que possible.', sendAnother: 'Envoyer un autre message', intro: 'Bonjour, je suis {name}. Laissez un message ci-dessous et un membre de l’équipe AllyJen vous répondra dès que possible.', urgentAllergen: 'Pour toute question urgente concernant les allergènes, veuillez vous adresser directement à un membre du personnel avant de commander.', yourName: 'Votre nom', replyEmail: 'E-mail pour notre réponse', howCanWeHelp: 'Comment pouvons-nous vous aider ?', website: 'Site web', sending: 'Envoi…', sendMessage: 'Envoyer le message',
    },
    adminPortal: {
      dashboard: 'Tableau de bord', ingredients: 'Ingrédients', newIngredient: 'Nouvel ingrédient', menuBuilder: 'Créateur de menu', newItem: 'Nouvel article', sites: 'Sites', newSite: 'Nouveau site', suppliers: 'Fournisseurs', analytics: 'Analyses', downloads: 'Téléchargements', accessPoints: 'Points d’accès', kioskDevices: 'Bornes', compliance: 'Conformité', foodSafety: 'Sécurité alimentaire', settings: 'Paramètres', helpSupport: 'Aide et assistance', superAdmin: 'Super-administration', admin: 'Administration', accessPointsDescription: 'Gérez la manière dont les clients accèdent à vos menus des allergènes.', activeQrCodes: 'Codes QR actifs', qrCodeSingular: '{count} code QR', qrCodePlural: '{count} codes QR', devicesOnline: '{online}/{total} appareils en ligne', openLocation: 'Ouvrir le site', manageQrAccessPoints: 'Gérer les points d’accès QR →',
    },
    accessPoints: {
      loadError: 'Impossible de charger les codes QR', createError: 'Impossible de créer le code QR', updateError: 'Impossible de modifier le code QR', deleteError: 'Impossible de supprimer le code QR', previewUnavailable: 'L’aperçu du code QR n’est pas disponible', imageError: 'Impossible de préparer l’image du code QR', signError: 'Impossible de créer l’affiche QR', loading: 'Chargement des codes QR…', qrLiteDescription: 'créez et téléchargez un code ci-dessous—aucune borne ni étape d’association n’est nécessaire.', qrCodes: 'Codes QR', active: 'Actif', inactive: 'Inactif', totalScans: 'Nombre total de scans', codesForSite: 'Codes QR pour {site}', createDescription: 'Créez des codes distincts pour les entrées, comptoirs, tables ou supports imprimés.', createQrCode: 'Créer un code QR', close: 'Fermer', site: 'Site', chooseSite: 'Choisissez un site…', name: 'Nom', namePlaceholder: 'Entrée principale', placement: 'Emplacement', optional: '(facultatif)', placementPlaceholder: 'Fenêtre près de la porte principale', cancel: 'Annuler', creating: 'Création…', create: 'Créer', emptyTitle: 'Aucun code QR pour le moment', emptyDescription: 'Créez-en un pour donner aux clients un accès mobile sans installer de matériel.', scans: 'scans', lastScanned: 'Dernier scan le {date}', notScanned: 'Pas encore scanné', copied: 'Copié', copy: 'Copier', open: 'Ouvrir', deactivate: 'Désactiver', activate: 'Activer', delete: 'Supprimer', deleteConfirm: 'Supprimer « {name} » ? Son code QR imprimé ne sera plus suivi.', signTitle: 'Scannez pour consulter les informations sur les allergènes', signDescription: 'Ouvrez le menu des allergènes AllyJen en direct sur votre téléphone. Aucune application requise.',
    },
  },
  es: {
    messaging: {
      sendError: 'No se pudo enviar tu mensaje.', messageSent: 'Mensaje enviado', thanks: 'Gracias por ponerte en contacto. Nuestro equipo responderá lo antes posible.', sendAnother: 'Enviar otro mensaje', intro: 'Hola, soy {name}. Deja un mensaje a continuación y un miembro del equipo de AllyJen responderá lo antes posible.', urgentAllergen: 'Para preguntas urgentes sobre alérgenos, habla directamente con un miembro del personal antes de pedir.', yourName: 'Tu nombre', replyEmail: 'Correo para nuestra respuesta', howCanWeHelp: '¿Cómo podemos ayudarte?', website: 'Sitio web', sending: 'Enviando…', sendMessage: 'Enviar mensaje',
    },
    adminPortal: {
      dashboard: 'Panel de control', ingredients: 'Ingredientes', newIngredient: 'Nuevo ingrediente', menuBuilder: 'Creador de menús', newItem: 'Nuevo artículo', sites: 'Sitios', newSite: 'Nuevo sitio', suppliers: 'Proveedores', analytics: 'Analíticas', downloads: 'Descargas', accessPoints: 'Puntos de acceso', kioskDevices: 'Dispositivos de quiosco', compliance: 'Cumplimiento', foodSafety: 'Seguridad alimentaria', settings: 'Configuración', helpSupport: 'Ayuda y soporte', superAdmin: 'Superadministración', admin: 'Administración', accessPointsDescription: 'Gestiona cómo acceden los clientes a tus menús de alérgenos.', activeQrCodes: 'Códigos QR activos', qrCodeSingular: '{count} código QR', qrCodePlural: '{count} códigos QR', devicesOnline: '{online}/{total} dispositivos en línea', openLocation: 'Abrir sitio', manageQrAccessPoints: 'Gestionar puntos de acceso QR →',
    },
    accessPoints: {
      loadError: 'No se pudieron cargar los códigos QR', createError: 'No se pudo crear el código QR', updateError: 'No se pudo actualizar el código QR', deleteError: 'No se pudo eliminar el código QR', previewUnavailable: 'La vista previa del código QR no está disponible', imageError: 'No se pudo preparar la imagen del código QR', signError: 'No se pudo crear el cartel QR', loading: 'Cargando códigos QR…', qrLiteDescription: 'crea y descarga un código a continuación; no se necesita un dispositivo de quiosco ni emparejamiento.', qrCodes: 'Códigos QR', active: 'Activos', inactive: 'Inactivo', totalScans: 'Escaneos totales', codesForSite: 'Códigos QR para {site}', createDescription: 'Crea códigos separados para entradas, mostradores, mesas o material impreso.', createQrCode: 'Crear código QR', close: 'Cerrar', site: 'Sitio', chooseSite: 'Elige un sitio…', name: 'Nombre', namePlaceholder: 'Entrada principal', placement: 'Ubicación', optional: '(opcional)', placementPlaceholder: 'Ventana junto a la puerta principal', cancel: 'Cancelar', creating: 'Creando…', create: 'Crear', emptyTitle: 'Aún no hay códigos QR', emptyDescription: 'Crea uno para dar acceso móvil a los clientes sin configurar hardware.', scans: 'escaneos', lastScanned: 'Último: {date}', notScanned: 'Aún no se ha escaneado', copied: 'Copiado', copy: 'Copiar', open: 'Abrir', deactivate: 'Desactivar', activate: 'Activar', delete: 'Eliminar', deleteConfirm: '¿Eliminar «{name}»? Su código QR impreso dejará de registrarse.', signTitle: 'Escanea para consultar información sobre alérgenos', signDescription: 'Abre el menú de alérgenos de AllyJen en directo en tu teléfono. No necesitas ninguna aplicación.',
    },
  },
  de: {
    messaging: {
      sendError: 'Ihre Nachricht konnte nicht gesendet werden.', messageSent: 'Nachricht gesendet', thanks: 'Vielen Dank für Ihre Nachricht. Unser Team antwortet so schnell wie möglich.', sendAnother: 'Weitere Nachricht senden', intro: 'Hallo, ich bin {name}. Hinterlassen Sie unten eine Nachricht; ein Mitglied des AllyJen-Teams antwortet so schnell wie möglich.', urgentAllergen: 'Bei dringenden Fragen zu Allergenen wenden Sie sich bitte vor der Bestellung direkt an einen Mitarbeiter.', yourName: 'Ihr Name', replyEmail: 'E-Mail-Adresse für unsere Antwort', howCanWeHelp: 'Wie können wir helfen?', website: 'Website', sending: 'Wird gesendet…', sendMessage: 'Nachricht senden',
    },
    adminPortal: {
      dashboard: 'Dashboard', ingredients: 'Zutaten', newIngredient: 'Neue Zutat', menuBuilder: 'Menü-Editor', newItem: 'Neuer Artikel', sites: 'Standorte', newSite: 'Neuer Standort', suppliers: 'Lieferanten', analytics: 'Analysen', downloads: 'Downloads', accessPoints: 'Zugangspunkte', kioskDevices: 'Kioskgeräte', compliance: 'Compliance', foodSafety: 'Lebensmittelsicherheit', settings: 'Einstellungen', helpSupport: 'Hilfe und Support', superAdmin: 'Super-Admin', admin: 'Administration', accessPointsDescription: 'Verwalten Sie, wie Kunden auf Ihre Allergenmenüs zugreifen.', activeQrCodes: 'Aktive QR-Codes', qrCodeSingular: '{count} QR-Code', qrCodePlural: '{count} QR-Codes', devicesOnline: '{online}/{total} Geräte online', openLocation: 'Standort öffnen', manageQrAccessPoints: 'QR-Zugangspunkte verwalten →',
    },
    accessPoints: {
      loadError: 'QR-Codes konnten nicht geladen werden', createError: 'QR-Code konnte nicht erstellt werden', updateError: 'QR-Code konnte nicht aktualisiert werden', deleteError: 'QR-Code konnte nicht gelöscht werden', previewUnavailable: 'Die QR-Code-Vorschau ist nicht verfügbar', imageError: 'Das QR-Code-Bild konnte nicht vorbereitet werden', signError: 'Das QR-Schild konnte nicht erstellt werden', loading: 'QR-Codes werden geladen…', qrLiteDescription: 'Erstellen und laden Sie unten einen Code herunter—ein Kioskgerät oder eine Kopplung ist nicht erforderlich.', qrCodes: 'QR-Codes', active: 'Aktiv', inactive: 'Inaktiv', totalScans: 'Scans insgesamt', codesForSite: 'QR-Codes für {site}', createDescription: 'Erstellen Sie separate Codes für Eingänge, Theken, Tische oder Druckmaterialien.', createQrCode: 'QR-Code erstellen', close: 'Schließen', site: 'Standort', chooseSite: 'Standort auswählen…', name: 'Name', namePlaceholder: 'Haupteingang', placement: 'Platzierung', optional: '(optional)', placementPlaceholder: 'Fenster neben der Haupteingangstür', cancel: 'Abbrechen', creating: 'Wird erstellt…', create: 'Erstellen', emptyTitle: 'Noch keine QR-Codes', emptyDescription: 'Erstellen Sie einen Code, um Kunden mobilen Zugriff ohne zusätzliche Hardware zu geben.', scans: 'Scans', lastScanned: 'Zuletzt am {date}', notScanned: 'Noch nicht gescannt', copied: 'Kopiert', copy: 'Kopieren', open: 'Öffnen', deactivate: 'Deaktivieren', activate: 'Aktivieren', delete: 'Löschen', deleteConfirm: '„{name}“ löschen? Der gedruckte QR-Code wird dann nicht mehr erfasst.', signTitle: 'Scannen für Allergeninformationen', signDescription: 'Öffnen Sie das aktuelle AllyJen-Allergenmenü auf Ihrem Smartphone. Keine App erforderlich.',
    },
  },
} as const
