type Guide = { title: string; description: string; steps: string[] }
export const quickAddHelp: Record<string, Guide> = {
  en: {
    title: 'Quick Add: deliveries, label photos and approval',
    description: 'Capture ingredients or bought-in products on a phone, tablet or computer; resume drafts, retry photos and send items for manager review.',
    steps: [
      'Find Quick Add on the Dashboard, Ingredients or Menu Builder. The same workflow works on computers, tablets and phones. Select Ingredient or Bought-in product and enter the product name. Delivery location, supplier and notes are optional at capture time. Open Allergens and dietary tags to enter known label details before saving; unanswered allergens stay Not reviewed.',
      'Select Save draft before adding photos. A draft is unassessed and cannot enter recipes or customer menus. Unknown suppliers remain text until the reviewer selects a supplier record.',
      'Use Take photo or Choose photos to attach up to 12 readable label images. Include the ingredient declaration and allergen information. JPEG, PNG and WebP work; HEIC requires browser support. If a format fails, take a new photo or choose JPEG. Open previews to check readability.',
      'Photos save individually. If an upload fails, select Try again; your text draft is kept. After closing the screen, remove any interrupted upload and select the photo again. Add another keeps the supplier/location and clears the product details and photos.',
      'Use Saved drafts to resume an item. Staff see their own captures; owners and managers see the business captures. Save text changes and finish or remove pending uploads, then select Send for review. You can Withdraw to draft before approval.',
      'Owners and managers filter Saved drafts by Ready for review. Open the photos, select a supplier, and assess every allergen. Missing values mean Not reviewed. Relevant gluten/nut subtypes also need assessment. For bought-in products, enter the ingredient declaration, confirm the label check and choose all locations or one location.',
      'Confirm that the photos are readable and support the assessment. Verify any selected dietary tags against the label or supporting evidence. Save review details, then Approve for use. A reviewer can instead enter a reason and Return for changes. Review history records submission, returns and approval. Owners/managers may approve their own entries.',
      'Approval creates a new ingredient for recipes or an inactive bought-in product. Publishing a bought-in product is a separate action in Menu Builder. Only dietary tags explicitly verified by the reviewer are carried into the approved record. Use Open resulting record for later changes; the label evidence remains private to the business.',
    ],
  },
  ga: {
    title: 'Quick Add: seachadtaí, grianghraif lipéad agus ceadú',
    description: 'Gabh comhábhair nó táirgí ceannaithe ar fhón, táibléad nó ríomhaire; lean le dréachtaí agus seol iad chuig bainisteoir.',
    steps: [
      'Oscail Quick Add ar an bPainéal, faoi Chomhábhair nó sa Tógálaí Biachláir. Oibríonn sé ar ríomhaire, táibléad agus fón. Roghnaigh Ingredient nó Bought-in product agus cuir ainm an táirge isteach. Tá suíomh an tseachadta, soláthraí agus nótaí roghnach. Oscail Allergens and dietary tags chun sonraí atá ar eolas agat a chur isteach roimh shábháil; fanann luachanna eile mar Not reviewed.',
      'Roghnaigh Save draft sula gcuireann tú grianghraif leis. Ní dhéantar measúnú ar dhréacht fós agus ní féidir é a úsáid in oidis ná ar bhiachláir do chustaiméirí. Fanann ainm soláthraí nua mar théacs go dtí an t-athbhreithniú.',
      'Úsáid Take photo nó Choose photos chun suas le 12 ghrianghraf inléite den lipéad a chur leis. Cuir an liosta comhábhar agus faisnéis ailléirginí san áireamh. Tacaítear le JPEG, PNG agus WebP; braitheann HEIC ar an mbrabhsálaí. Oscail na réamhamhairc chun inléiteacht a sheiceáil.',
      'Sábháiltear gach grianghraf ar leithligh. Má theipeann ar uaslódáil, roghnaigh Try again; coinnítear an dréacht téacs. Tar éis an scáileán a dhúnadh, bain an uaslódáil neamhiomlán agus roghnaigh an grianghraf arís. Coinníonn Add another an soláthraí agus an suíomh, ach glanann sé sonraí agus grianghraif an táirge.',
      'Oscail Saved drafts chun leanúint le mír. Feiceann baill foirne a ngabhálacha féin; feiceann úinéirí agus bainisteoirí gabhálacha an ghnó. Sábháil athruithe agus críochnaigh nó bain uaslódálacha atá ar feitheamh, ansin roghnaigh Send for review. Úsáid Withdraw to draft chun tarraingt siar roimh cheadú.',
      'Scagann úinéirí agus bainisteoirí de réir Ready for review. Seiceáil grianghraif, roghnaigh soláthraí agus déan measúnú ar gach ailléirgin agus ar na fochineálacha glútan/cnónna ábhartha. Ciallaíonn luach ar iarraidh Not reviewed. I gcás táirgí ceannaithe, cuir an dearbhú comhábhar isteach, deimhnigh an lipéad agus roghnaigh na suíomhanna.',
      'Deimhnigh go bhfuil na lipéid inléite agus go dtacaíonn siad leis an measúnú. Roghnaigh Save review details agus ansin Approve for use. Nó cuir cúis isteach agus roghnaigh Return for changes. Taifeadtar na gníomhartha sa stair; is féidir le húinéirí agus bainisteoirí a n-iontrálacha féin a cheadú.',
      'Cruthaíonn ceadú comhábhar nua d’oidis nó táirge ceannaithe neamhghníomhach. Is gníomh ar leith sa Tógálaí Biachláir é foilsiú. Ní aistrítear ach na clibeanna aiste bia atá fíoraithe ag an athbhreithneoir. Úsáid Open resulting record le haghaidh athruithe eile; fanann an fhianaise lipéid príobháideach don ghnó.',
    ],
  },
  pt: {
    title: 'Quick Add: entregas, fotografias e aprovação',
    description: 'Registe ingredientes ou produtos comprados no telemóvel, tablet ou computador; retome rascunhos e envie-os para revisão.',
    steps: [
      'Abra Quick Add no Painel, Ingredientes ou Menu Builder, em qualquer dispositivo. Escolha Ingredient ou Bought-in product e indique o nome. Local de entrega, fornecedor e notas são opcionais. Abra Allergens and dietary tags para preencher dados conhecidos antes de guardar; os restantes ficam Not reviewed.',
      'Selecione Save draft antes de adicionar fotografias. O rascunho não foi avaliado e não pode entrar em receitas nem menus de clientes. Um fornecedor desconhecido fica como texto até o revisor escolher um registo de fornecedor.',
      'Use Take photo ou Choose photos para adicionar até 12 imagens legíveis, incluindo a lista de ingredientes e os alergénios. São aceites JPEG, PNG e WebP; HEIC depende do navegador. Se falhar, tire outra fotografia ou escolha JPEG. Abra as pré-visualizações para verificar a leitura.',
      'Cada fotografia é guardada separadamente. Se falhar, use Try again; o texto mantém-se. Depois de fechar, remova o carregamento interrompido e selecione novamente a imagem. Add another mantém fornecedor/local e limpa os dados e fotografias do produto.',
      'Retome uma captura em Saved drafts. Os funcionários veem as próprias capturas; proprietários e gestores veem as da empresa. Guarde alterações e conclua ou remova carregamentos pendentes antes de Send for review. Pode usar Withdraw to draft antes da aprovação.',
      'Proprietários e gestores filtram por Ready for review. Abra as fotos, escolha um fornecedor e avalie todos os alergénios e subtipos relevantes de glúten/frutos de casca rija. Dados em falta significam Not reviewed. Para produtos comprados, transcreva os ingredientes, confirme o rótulo e escolha todos os locais ou um local.',
      'Confirme a legibilidade e a correspondência da avaliação com as fotos. Use Save review details e depois Approve for use. Para pedir correções, escreva o motivo e use Return for changes. O histórico regista as ações; gestores e proprietários podem aprovar as próprias entradas.',
      'A aprovação cria um ingrediente utilizável em receitas ou um produto comprado inativo. A publicação é uma ação separada no Menu Builder. Só são transferidas as etiquetas alimentares verificadas pelo revisor. Use Open resulting record para alterações posteriores; a prova do rótulo permanece privada à empresa.',
    ],
  },
  fr: {
    title: 'Quick Add : livraisons, photos et validation',
    description: 'Saisissez des ingrédients ou produits achetés sur téléphone, tablette ou ordinateur ; reprenez les brouillons et demandez une vérification.',
    steps: [
      'Ouvrez Quick Add depuis le Tableau de bord, Ingrédients ou Menu Builder, sur tout appareil. Choisissez Ingredient ou Bought-in product et saisissez le nom. Le lieu de livraison, le fournisseur et les notes sont facultatifs. Ouvrez Allergens and dietary tags pour saisir les données connues avant de sauvegarder ; les autres restent Not reviewed.',
      'Sélectionnez Save draft avant les photos. Le brouillon reste non évalué et ne peut entrer dans les recettes ni les menus clients. Un fournisseur inconnu reste du texte jusqu’à sa sélection dans les fiches fournisseurs.',
      'Utilisez Take photo ou Choose photos pour joindre jusqu’à 12 images lisibles, avec les ingrédients et les allergènes. JPEG, PNG et WebP sont acceptés ; HEIC dépend du navigateur. En cas d’échec, reprenez la photo ou choisissez JPEG. Ouvrez les aperçus pour vérifier la lisibilité.',
      'Chaque photo est enregistrée séparément. En cas d’échec, utilisez Try again ; le texte est conservé. Après fermeture, supprimez le transfert interrompu et sélectionnez à nouveau la photo. Add another conserve fournisseur/lieu et efface les données et photos du produit.',
      'Reprenez une saisie dans Saved drafts. Le personnel voit ses propres saisies ; propriétaires et responsables voient celles de l’entreprise. Enregistrez les modifications et terminez ou retirez les transferts en attente avant Send for review. Withdraw to draft permet un retrait avant validation.',
      'Les responsables filtrent sur Ready for review. Consultez les photos, choisissez un fournisseur et évaluez chaque allergène, avec les sous-types pertinents de gluten/fruits à coque. Une valeur absente signifie Not reviewed. Pour les produits achetés, saisissez les ingrédients, confirmez le contrôle de l’étiquette et choisissez les sites.',
      'Confirmez la lisibilité des photos et leur concordance avec l’évaluation. Utilisez Save review details puis Approve for use. Pour demander des corrections, indiquez le motif et choisissez Return for changes. L’historique conserve les actions ; les responsables peuvent valider leurs propres saisies.',
      'La validation crée un ingrédient utilisable dans les recettes ou un produit acheté inactif. Sa publication reste une action distincte dans Menu Builder. Seules les mentions alimentaires vérifiées par le responsable sont transférées. Utilisez Open resulting record pour les changements ultérieurs ; les preuves restent privées à l’entreprise.',
    ],
  },
  es: {
    title: 'Quick Add: entregas, fotos y aprobación',
    description: 'Registre ingredientes o productos comprados desde móvil, tableta u ordenador; retome borradores y envíelos para revisión.',
    steps: [
      'Abra Quick Add desde el Panel, Ingredientes o Menu Builder en cualquier dispositivo. Elija Ingredient o Bought-in product e indique el nombre. El lugar de entrega, proveedor y notas son opcionales. Abra Allergens and dietary tags para introducir los datos conocidos antes de guardar; los demás quedan Not reviewed.',
      'Seleccione Save draft antes de añadir fotos. El borrador sigue sin evaluar y no puede usarse en recetas ni menús de clientes. Un proveedor desconocido queda como texto hasta que el revisor elige su ficha.',
      'Use Take photo o Choose photos para adjuntar hasta 12 imágenes legibles con los ingredientes y alérgenos. Se admiten JPEG, PNG y WebP; HEIC depende del navegador. Si falla, tome otra foto o use JPEG. Abra las vistas previas para comprobar la lectura.',
      'Cada foto se guarda por separado. Si falla, use Try again; el texto se conserva. Tras cerrar la pantalla, elimine la carga interrumpida y seleccione otra vez la foto. Add another conserva proveedor/ubicación y borra los datos y fotos del producto.',
      'Retome una captura en Saved drafts. El personal ve sus capturas; propietarios y responsables ven las de la empresa. Guarde los cambios y complete o elimine las cargas pendientes antes de Send for review. Use Withdraw to draft para retirarla antes de la aprobación.',
      'Los responsables filtran por Ready for review. Abra las fotos, elija un proveedor y evalúe cada alérgeno y los subtipos pertinentes de gluten/frutos de cáscara. Un dato ausente significa Not reviewed. Para productos comprados, transcriba los ingredientes, confirme la etiqueta y elija las ubicaciones.',
      'Confirme que las fotos son legibles y respaldan la evaluación. Use Save review details y después Approve for use. Para pedir cambios, indique el motivo y use Return for changes. El historial registra las acciones; los responsables pueden aprobar sus propias entradas.',
      'La aprobación crea un ingrediente utilizable en recetas o un producto comprado inactivo. Publicarlo es una acción separada en Menu Builder. Solo se transfieren las etiquetas dietéticas verificadas por el responsable. Use Open resulting record para cambios posteriores; las pruebas permanecen privadas para la empresa.',
    ],
  },
  de: {
    title: 'Quick Add: Lieferungen, Etikettfotos und Freigabe',
    description: 'Zutaten oder zugekaufte Produkte am Handy, Tablet oder Computer erfassen; Entwürfe fortsetzen und zur Prüfung einreichen.',
    steps: [
      'Öffnen Sie Quick Add im Dashboard, unter Zutaten oder im Menu Builder. Wählen Sie Ingredient oder Bought-in product und geben Sie den Namen ein. Lieferort, Lieferant und Notizen sind optional. Öffnen Sie Allergens and dietary tags, um bekannte Angaben vor dem Speichern einzutragen; fehlende Angaben bleiben Not reviewed.',
      'Wählen Sie vor dem Hinzufügen von Fotos Save draft. Der Entwurf ist noch nicht bewertet und steht weder Rezepten noch Kundenmenüs zur Verfügung. Unbekannte Lieferanten bleiben Text, bis bei der Prüfung ein Lieferantendatensatz gewählt wird.',
      'Mit Take photo oder Choose photos fügen Sie bis zu 12 lesbare Bilder einschließlich Zutatenliste und Allergenangaben hinzu. JPEG, PNG und WebP werden unterstützt; HEIC hängt vom Browser ab. Bei Problemen erneut fotografieren oder JPEG wählen. Prüfen Sie die Lesbarkeit in der Vorschau.',
      'Fotos werden einzeln gespeichert. Bei Fehlern Try again wählen; der Text bleibt erhalten. Nach dem Schließen einen unterbrochenen Upload entfernen und das Foto erneut auswählen. Add another behält Lieferant/Standort und leert Produktangaben und Fotos.',
      'Unter Saved drafts setzen Sie eine Erfassung fort. Mitarbeitende sehen eigene Erfassungen, Inhaber und Manager die des Unternehmens. Änderungen speichern und ausstehende Uploads abschließen oder entfernen, dann Send for review wählen. Vor der Freigabe ist Withdraw to draft möglich.',
      'Prüfende filtern nach Ready for review. Fotos öffnen, Lieferanten wählen und jedes Allergen sowie relevante Gluten-/Nussuntertypen bewerten. Fehlende Werte bedeuten Not reviewed. Bei zugekauften Produkten Zutatenliste eingeben, Etikettprüfung bestätigen und alle Standorte oder einen Standort wählen.',
      'Bestätigen Sie Lesbarkeit und Übereinstimmung der Bewertung mit den Fotos. Wählen Sie Save review details und danach Approve for use. Für Korrekturen einen Grund eingeben und Return for changes wählen. Der Verlauf erfasst die Aktionen; Manager und Inhaber dürfen eigene Einträge freigeben.',
      'Die Freigabe erstellt eine neue Rezeptzutat oder ein inaktives zugekauftes Produkt. Die Veröffentlichung erfolgt separat im Menu Builder. Es werden keine Ernährungsangaben hinzugefügt. Spätere Änderungen erfolgen über Open resulting record; Etikettbelege bleiben unternehmensintern.',
    ],
  },
}
